services:
  - docker

env:
  global:
    - DOCKER_TAG=jarokelo/php-nginx:php71
    - secure: IMdefippM1jDvet5qtrFnC/kmzIyyh7Z9WBjtDUOF9PI8+ZWkPlPaMDMEzHS7dLcQz8i3FWAPAaZ+g1kyM5ve7IkeiAlRvQXXnuc1LObOV2lwdDciNOfHihy3STJLebu0+SJwv2HQvbRxhk9kgtfl+B4AA14Bj5ULn6++cRGexMGjJbxfCHIzeOxar4P4zPsflJ8gl/WrRjeEdu2/NM2qPnGvra4/HhxFT/SrPzuvVBQCUHf+gnnorQ8k4Y1Zv15q+cQmA3H68ZmsZqVZKK+F+3vxA3uscxc2T1biJWPb57oZ0dz5h83v9QqTJNgfqFwHYRfTQuV/UF75+jtW36P98GC3tIF3FClK7R7QXouVWWF7j6XH0SfYnWxygZhVv7MkqoOq/Ijw4UM5Mi68D55MTev5L6tTS2YLMba06idgET3+ZoikeoLxZ4lu3BIijxfJFVQ8Jqv/nJbKgBwQjV6TGYUS6FO0bl8hwxgdtqvZ/ah/SGXflp19rIHEoNLnLYTE4ivcFk3Pj4De86MoiUDt0Fkks4SWsKTJILtN5VdMAlO1tsR0IKXU8fOnfQGRGZzyIXyaDhXxWty7piU9BiS1cTG6Mn97TO72ULpNsGKvXSIS20t4Ut/e+sgWNgY7iQNO9bfbzG85Zp68ob38/gy0aBKRwdaOyy8dDB4CTv4pn0=
    - secure: FMJG8QYwxLBLDbM96Yc5g6VJYwjR2xrYrPCRbDH+hzNuI4dukOe61u94sEtPYOoPKer04sZb0DOoQEOlNxsT/Qh4V+BSRP2+ltcx2r5XBcboiZQaDF49d+QDq2OYDsIetN0CTNv8GOjrrnsFRvBNBAGZukT/tQufuqdsl9rGU+lgQ7Zu2L8Y5Dtfzx7goy3aumixGpBa5fMg+ixEEm8rCZDJmVxv9KBNt7Ig04OqJ8SqV/mD8IeKhPciVm4yP29V5RXgkqz4yUxlYwbi3Lpbxkl62c30ACjykwEMY4Tu7ApJD0rHBsjFbETUUGwYjsf6QPBwmRklU3seYMxnxClAewtryK0DhAr/mG+QAD99HgYn8414cZp2FNGYlhNXo4tMUKPSS6UdoUtVY8e1cGzLkkjsktfkmhU4eFD2WfrGFO3ciz4CtTpl3ua2vKJU/tkWP5gfL1kW45jONFwqEk0s4SQ98x45h+5t92i23f0w1e/y39GaYTCq0XuyWOPC2RCk/pXApwOZjOwaOvzJS4EjO1Zm5L2bYxK8s10gUyaobIQwi/ttg3Kclt9GtwB1jFP8q8Py6FTc7hyyKCHdN+bD7+mPEYx2lPBmGgtoWkq/xZyqfR4WFoImxks7dJ7NzcW/+H49pfgdZcStN6j6eimqWNdy1O73/n58Zo5PmopAE4s=

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull jarokelo/debian:stretch
  - 'docker pull "${DOCKER_TAG}-dev"'

script:
  - 'docker build -t "${DOCKER_TAG}" .'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker push "${DOCKER_TAG}"'
  - 'docker build -t "${DOCKER_TAG}-dev" -f Dockerfile.dev .'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker push "${DOCKER_TAG}-dev"'
  - echo "Build finished."
